# funasr 的基础镜像

FROM nvcr.io/nvidia/tritonserver:23.01-py3
# https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html
# Please choose previous tritonserver:xx.xx if you encounter cuda driver mismatch issue

LABEL maintainer="NVIDIA"
LABEL repository="tritonserver"

CMD cat <<'EOF' > /etc/apt/sources.list \
# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释 \
deb https://mirrors.cernet.edu.cn/ubuntu/ focal main restricted universe multiverse \
deb https://mirrors.cernet.edu.cn/ubuntu/ focal-updates main restricted universe multiverse \
deb https://mirrors.cernet.edu.cn/ubuntu/ focal-backports main restricted universe multiverse \
deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse \
EOF

RUN apt-get update  && apt-get -y install \
    python3-dev \
    cmake \
    libsndfile1

# -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install torch torchaudio -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install kaldifeat pyyaml -i https://pypi.tuna.tsinghua.edu.cn/simple

# Dependency for client
RUN pip3 install soundfile grpcio-tools tritonclient -i https://pypi.tuna.tsinghua.edu.cn/simple
WORKDIR /workspace
