services:
 facefusion-cuda:
  build:
   context: .
   dockerfile: Dockerfile.cuda
  command: [ 'python', 'run.py', '--execution-providers', 'cuda','--ui-layouts', 'default','--log-level','debug' ]
  volumes:
  - .assets:/facefusion/.assets
  ports:
  - 7880:7860
  deploy:
   resources:
    reservations:
     devices:
     - driver: nvidia
       capabilities: [ gpu ]
       device_ids: ['3']
